# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

environment:
  global:
      # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
      # /E:ON and /V:ON options are not enabled in the batch script intepreter
      # See: http://stackoverflow.com/a/13751649/163740
      CMD_IN_ENV: 'cmd /E:ON /V:ON /C .\tools\appveyor\run_with_env.cmd'
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CONDA_DEPENDENCIES: "setuptools numpy scipy pandas nose h5py coverage"
      PIP_DEPENDENCIES: "tables codecov"
  matrix:
      - PYTHON_VERSION: "3.6"
        PYTHON_ARCH: "64"

version: '{build}'

install:
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "activate test"
  - "python setup.py develop"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Run the project tests
  - "nosetests"

on_success:
  - "codecov"
